In [1]:
import numpy as np

In [34]:
# task 01 : to create an 2D array from 1-30
temp=np.arange(30)+1
main_arr= temp.reshape(6,5)

# task 02 : to check the indexing of [1::1,1::1] vs. [[0,1,2,3].[1,2,3,4]]
main_arr[[0,1,2,3],[1,2,3,4]]

# task 03 : index 4,5 24,25, 29,30
print(main_arr)
main_arr[[0,4,5],3:]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[ 4,  5],
       [24, 25],
       [29, 30]])